# Eigen Decomposition vs Singular Value Decomposition

In [ ]:
import numpy as np
import torch

### SVD by Numpy

In [8]:
A = np.random.randn(5, 3)
print(A)

[[ 0.0307883   1.26916929  0.78212227]
 [ 0.4657832   0.77049058  0.53491485]
 [ 0.22755684  0.03160206  1.0147652 ]
 [-1.92543727 -1.63114219  0.06700461]
 [-0.6602673   0.36404303  0.31565601]]


In [9]:
U, S, Vt = np.linalg.svd(A)

In [13]:
U.shape, S.shape, Vt.shape

((5, 5), (3,), (3, 3))

In [10]:
U.dot(U.T)

array([[ 1.00000000e+00,  1.38777878e-17, -1.11022302e-16,
         2.22044605e-16,  2.77555756e-17],
       [ 1.38777878e-17,  1.00000000e+00, -1.38777878e-16,
         1.66533454e-16, -5.55111512e-17],
       [-1.11022302e-16, -1.38777878e-16,  1.00000000e+00,
        -6.93889390e-17, -2.77555756e-17],
       [ 2.22044605e-16,  1.66533454e-16, -6.93889390e-17,
         1.00000000e+00, -2.22044605e-16],
       [ 2.77555756e-17, -5.55111512e-17, -2.77555756e-17,
        -2.22044605e-16,  1.00000000e+00]])

In [11]:
Vt.dot(Vt.T)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
np.linalg.matrix_rank(A)

np.int64(3)

In [17]:
Sf = np.zeros(A.shape)

In [24]:
Sf[:3, :3] = np.diag(S)

In [25]:
U.dot(Sf).dot(Vt)

array([[ 0.0307883 ,  1.26916929,  0.78212227],
       [ 0.4657832 ,  0.77049058,  0.53491485],
       [ 0.22755684,  0.03160206,  1.0147652 ],
       [-1.92543727, -1.63114219,  0.06700461],
       [-0.6602673 ,  0.36404303,  0.31565601]])

### Eigen Decomposition vs Singular Value Decomposition

Calculate Eigen Value and Eigen Vector

In [143]:
A = torch.randint(0, 10, (3, 3)).float()
A = (A + A.T)/2
A

tensor([[4.0000, 8.5000, 3.5000],
        [8.5000, 2.0000, 5.5000],
        [3.5000, 5.5000, 0.0000]])

In [154]:
B = torch.randn(3, 3)
B

tensor([[ 1.8804,  0.5209,  1.9402],
        [-0.6406, -0.3380,  0.5921],
        [ 1.1248, -2.4895,  0.2965]])

In [156]:
a_eigenvalues, a_eigenvectors = torch.linalg.eigh(A)
a_eigenvalues, a_eigenvectors

(tensor([-6.3292, -2.0035, 14.3327]),
 tensor([[-0.5014,  0.5609, -0.6588],
         [ 0.7710, -0.0560, -0.6344],
         [-0.3927, -0.8260, -0.4043]]))

In [159]:
b_eigenvalues, b_eigenvectors = torch.linalg.eigh(B)
b_eigenvalues, b_eigenvectors

(tensor([-2.5472,  0.8935,  3.4926]),
 tensor([[ 0.0638,  0.7816, -0.6206],
         [-0.7382,  0.4554,  0.4976],
         [-0.6715, -0.4264, -0.6060]]))

Reconstructed A by Eigen Value and Eigen Vector

In [161]:
A_hat = a_eigenvectors @ torch.diag(a_eigenvalues) @ a_eigenvectors.T
A_hat

tensor([[ 4.0000e+00,  8.5000e+00,  3.5000e+00],
        [ 8.5000e+00,  2.0000e+00,  5.5000e+00],
        [ 3.5000e+00,  5.5000e+00, -4.7684e-07]])

In [162]:
torch.norm(A - A_hat)

tensor(4.1706e-06)

In [164]:
B_hat = b_eigenvectors @ torch.diag(b_eigenvalues) @ b_eigenvectors.T
B_hat

tensor([[ 1.8804, -0.6406,  1.1248],
        [-0.6406, -0.3380, -2.4895],
        [ 1.1248, -2.4895,  0.2965]])

In [166]:
torch.norm(B - B_hat)

tensor(3.3926)

Calculate singular vector and singular value

In [168]:
a_U, a_S, a_Vt = torch.linalg.svd(A, full_matrices = True)
a_U.shape, a_S.shape, a_Vt.shape, a_U, a_S, a_Vt

(torch.Size([3, 3]),
 torch.Size([3]),
 torch.Size([3, 3]),
 tensor([[-0.6588,  0.5014, -0.5609],
         [-0.6344, -0.7710,  0.0560],
         [-0.4043,  0.3927,  0.8260]]),
 tensor([14.3327,  6.3292,  2.0035]),
 tensor([[-0.6588, -0.6344, -0.4043],
         [-0.5014,  0.7710, -0.3927],
         [ 0.5609, -0.0560, -0.8260]]))

In [169]:
a_S_full = torch.zeros(A.shape, dtype=a_S.dtype)
a_S_full[:3, :3] = torch.diag(a_S)
A_reconstructed = a_U @ a_S_full @ a_Vt
A_reconstructed

tensor([[4.0000e+00, 8.5000e+00, 3.5000e+00],
        [8.5000e+00, 2.0000e+00, 5.5000e+00],
        [3.5000e+00, 5.5000e+00, 3.5763e-07]])

In [173]:
torch.norm(A - A_reconstructed)

tensor(5.4797e-06)

In [171]:
b_U, b_S, b_Vt = torch.linalg.svd(B, full_matrices = True)
b_U.shape, b_S.shape, b_Vt.shape, b_U, b_S, b_Vt

(torch.Size([3, 3]),
 torch.Size([3]),
 torch.Size([3, 3]),
 tensor([[-0.7092, -0.7036,  0.0455],
         [-0.0055,  0.0701,  0.9975],
         [-0.7050,  0.7072, -0.0536]]),
 tensor([2.9925, 2.4887, 0.9212]),
 tensor([[-0.7094,  0.4637, -0.5308],
         [-0.2300, -0.8642, -0.4476],
         [-0.6662, -0.1954,  0.7197]]))

In [176]:
b_S_full = torch.zeros(A.shape, dtype=b_S.dtype)
b_S_full[:3, :3] = torch.diag(b_S)
B_reconstructed = b_U @ b_S_full @ b_Vt
B_reconstructed

tensor([[ 1.8804,  0.5209,  1.9402],
        [-0.6406, -0.3380,  0.5921],
        [ 1.1248, -2.4895,  0.2965]])

In [178]:
torch.norm(B - B_reconstructed)

tensor(2.0112e-06)

 Verifying SVD from ED

In [181]:
ATA = A.T @ A
eigvals, V = torch.linalg.eigh(ATA)
S = torch.sqrt(eigvals.clamp(min=1e-10))
Sigma = torch.diag(S)

# Step 2: U = A V Σ⁻¹
U = A @ V @ torch.linalg.inv(Sigma)

# Step 3: Reconstruct A
A_hat = U @ Sigma @ V.T
torch.norm(A - A_hat)

tensor(4.5111e-06)