# Eigen Decomposition vs Singular Value Decomposition

In [184]:
import numpy as np
import torch

### SVD by Numpy

In [8]:
A = np.random.randn(5, 3)
print(A)

[[ 0.0307883   1.26916929  0.78212227]
 [ 0.4657832   0.77049058  0.53491485]
 [ 0.22755684  0.03160206  1.0147652 ]
 [-1.92543727 -1.63114219  0.06700461]
 [-0.6602673   0.36404303  0.31565601]]


In [9]:
U, S, Vt = np.linalg.svd(A)

In [13]:
U.shape, S.shape, Vt.shape

((5, 5), (3,), (3, 3))

In [10]:
U.dot(U.T)

array([[ 1.00000000e+00,  1.38777878e-17, -1.11022302e-16,
         2.22044605e-16,  2.77555756e-17],
       [ 1.38777878e-17,  1.00000000e+00, -1.38777878e-16,
         1.66533454e-16, -5.55111512e-17],
       [-1.11022302e-16, -1.38777878e-16,  1.00000000e+00,
        -6.93889390e-17, -2.77555756e-17],
       [ 2.22044605e-16,  1.66533454e-16, -6.93889390e-17,
         1.00000000e+00, -2.22044605e-16],
       [ 2.77555756e-17, -5.55111512e-17, -2.77555756e-17,
        -2.22044605e-16,  1.00000000e+00]])

In [11]:
Vt.dot(Vt.T)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
np.linalg.matrix_rank(A)

np.int64(3)

In [17]:
Sf = np.zeros(A.shape)

In [24]:
Sf[:3, :3] = np.diag(S)

In [25]:
U.dot(Sf).dot(Vt)

array([[ 0.0307883 ,  1.26916929,  0.78212227],
       [ 0.4657832 ,  0.77049058,  0.53491485],
       [ 0.22755684,  0.03160206,  1.0147652 ],
       [-1.92543727, -1.63114219,  0.06700461],
       [-0.6602673 ,  0.36404303,  0.31565601]])

### Eigen Decomposition vs Singular Value Decomposition

Calculate Eigen Value and Eigen Vector

In [143]:
A = torch.randint(0, 10, (3, 3)).float()
A = (A + A.T)/2
A

tensor([[4.0000, 8.5000, 3.5000],
        [8.5000, 2.0000, 5.5000],
        [3.5000, 5.5000, 0.0000]])

In [154]:
B = torch.randn(3, 3)
B

tensor([[ 1.8804,  0.5209,  1.9402],
        [-0.6406, -0.3380,  0.5921],
        [ 1.1248, -2.4895,  0.2965]])

In [156]:
a_eigenvalues, a_eigenvectors = torch.linalg.eigh(A)
a_eigenvalues, a_eigenvectors

(tensor([-6.3292, -2.0035, 14.3327]),
 tensor([[-0.5014,  0.5609, -0.6588],
         [ 0.7710, -0.0560, -0.6344],
         [-0.3927, -0.8260, -0.4043]]))

In [159]:
b_eigenvalues, b_eigenvectors = torch.linalg.eigh(B)
b_eigenvalues, b_eigenvectors

(tensor([-2.5472,  0.8935,  3.4926]),
 tensor([[ 0.0638,  0.7816, -0.6206],
         [-0.7382,  0.4554,  0.4976],
         [-0.6715, -0.4264, -0.6060]]))

Reconstructed A by Eigen Value and Eigen Vector

In [161]:
A_hat = a_eigenvectors @ torch.diag(a_eigenvalues) @ a_eigenvectors.T
A_hat

tensor([[ 4.0000e+00,  8.5000e+00,  3.5000e+00],
        [ 8.5000e+00,  2.0000e+00,  5.5000e+00],
        [ 3.5000e+00,  5.5000e+00, -4.7684e-07]])

In [162]:
torch.norm(A - A_hat)

tensor(4.1706e-06)

In [164]:
B_hat = b_eigenvectors @ torch.diag(b_eigenvalues) @ b_eigenvectors.T
B_hat

tensor([[ 1.8804, -0.6406,  1.1248],
        [-0.6406, -0.3380, -2.4895],
        [ 1.1248, -2.4895,  0.2965]])

In [166]:
torch.norm(B - B_hat)

tensor(3.3926)

Calculate singular vector and singular value

In [168]:
a_U, a_S, a_Vt = torch.linalg.svd(A, full_matrices = True)
a_U.shape, a_S.shape, a_Vt.shape, a_U, a_S, a_Vt

(torch.Size([3, 3]),
 torch.Size([3]),
 torch.Size([3, 3]),
 tensor([[-0.6588,  0.5014, -0.5609],
         [-0.6344, -0.7710,  0.0560],
         [-0.4043,  0.3927,  0.8260]]),
 tensor([14.3327,  6.3292,  2.0035]),
 tensor([[-0.6588, -0.6344, -0.4043],
         [-0.5014,  0.7710, -0.3927],
         [ 0.5609, -0.0560, -0.8260]]))

In [169]:
a_S_full = torch.zeros(A.shape, dtype=a_S.dtype)
a_S_full[:3, :3] = torch.diag(a_S)
A_reconstructed = a_U @ a_S_full @ a_Vt
A_reconstructed

tensor([[4.0000e+00, 8.5000e+00, 3.5000e+00],
        [8.5000e+00, 2.0000e+00, 5.5000e+00],
        [3.5000e+00, 5.5000e+00, 3.5763e-07]])

In [173]:
torch.norm(A - A_reconstructed)

tensor(5.4797e-06)

In [171]:
b_U, b_S, b_Vt = torch.linalg.svd(B, full_matrices = True)
b_U.shape, b_S.shape, b_Vt.shape, b_U, b_S, b_Vt

(torch.Size([3, 3]),
 torch.Size([3]),
 torch.Size([3, 3]),
 tensor([[-0.7092, -0.7036,  0.0455],
         [-0.0055,  0.0701,  0.9975],
         [-0.7050,  0.7072, -0.0536]]),
 tensor([2.9925, 2.4887, 0.9212]),
 tensor([[-0.7094,  0.4637, -0.5308],
         [-0.2300, -0.8642, -0.4476],
         [-0.6662, -0.1954,  0.7197]]))

In [176]:
b_S_full = torch.zeros(A.shape, dtype=b_S.dtype)
b_S_full[:3, :3] = torch.diag(b_S)
B_reconstructed = b_U @ b_S_full @ b_Vt
B_reconstructed

tensor([[ 1.8804,  0.5209,  1.9402],
        [-0.6406, -0.3380,  0.5921],
        [ 1.1248, -2.4895,  0.2965]])

In [178]:
torch.norm(B - B_reconstructed)

tensor(2.0112e-06)

 Verifying SVD from ED

In [181]:
ATA = A.T @ A
eigvals, V = torch.linalg.eigh(ATA)
S = torch.sqrt(eigvals.clamp(min=1e-10))
Sigma = torch.diag(S)

# Step 2: U = A V Σ⁻¹
U = A @ V @ torch.linalg.inv(Sigma)

# Step 3: Reconstruct A
A_hat = U @ Sigma @ V.T
torch.norm(A - A_hat)

tensor(4.5111e-06)

## More

In [191]:
C = torch.randn(3, 5)
C

tensor([[-0.4823, -1.5105, -0.4407,  3.2276, -0.1590],
        [-0.9366,  0.0962, -2.0062,  0.1766,  1.9826],
        [-1.5003,  0.2550,  0.7925,  0.1977, -1.0079]])

In [192]:
U, s, Vt = torch.linalg.svd(C)
U, s, Vt

(tensor([[-0.9580,  0.2584, -0.1243],
         [-0.2863, -0.8851,  0.3669],
         [-0.0153,  0.3871,  0.9219]]),
 tensor([3.6872, 3.0627, 1.7458]),
 tensor([[ 0.2043,  0.3839,  0.2670, -0.8531, -0.1085],
         [ 0.0404, -0.1230,  0.6428,  0.2462, -0.7138],
         [-0.9548,  0.2625,  0.0283, -0.0884, -0.1043],
         [ 0.1650,  0.8174,  0.2262,  0.4493,  0.2271],
         [-0.1334, -0.3169,  0.6809, -0.0435,  0.6452]]))

In [194]:
S = torch.zeros(C.shape, dtype=s.dtype)
S[:3, :3] = torch.diag(s)
C_rec = U @ S @ Vt
C_rec


tensor([[-0.4823, -1.5105, -0.4407,  3.2276, -0.1590],
        [-0.9366,  0.0962, -2.0062,  0.1766,  1.9826],
        [-1.5003,  0.2550,  0.7925,  0.1977, -1.0079]])

In [197]:
torch.allclose(C_rec, C)

True

In [201]:
U

tensor([[-0.9580, -0.2863, -0.0153],
        [ 0.2584, -0.8851,  0.3871],
        [-0.1243,  0.3669,  0.9219]])

In [198]:
torch.linalg.eigh(C @ C.T)

torch.return_types.linalg_eigh(
eigenvalues=tensor([ 3.0477,  9.3799, 13.5955]),
eigenvectors=tensor([[-0.1243,  0.2584, -0.9580],
        [ 0.3669, -0.8851, -0.2863],
        [ 0.9219,  0.3871, -0.0153]]))

In [202]:
s ** 2

tensor([13.5955,  9.3799,  3.0477])

In [204]:
torch.linalg.eigh( C.T @ C)

torch.return_types.linalg_eigh(
eigenvalues=tensor([-1.4984e-07,  2.0023e-07,  3.0477e+00,  9.3799e+00,  1.3595e+01]),
eigenvectors=tensor([[-0.1605,  0.1388, -0.9548,  0.0404, -0.2043],
        [-0.4564,  0.7485,  0.2625, -0.1230, -0.3839],
        [ 0.6301,  0.3430,  0.0283,  0.6428, -0.2670],
        [-0.1222,  0.4345, -0.0884,  0.2462,  0.8531],
        [ 0.5949,  0.3377, -0.1043, -0.7138,  0.1085]]))

In [205]:
Vt

tensor([[ 0.2043,  0.3839,  0.2670, -0.8531, -0.1085],
        [ 0.0404, -0.1230,  0.6428,  0.2462, -0.7138],
        [-0.9548,  0.2625,  0.0283, -0.0884, -0.1043],
        [ 0.1650,  0.8174,  0.2262,  0.4493,  0.2271],
        [-0.1334, -0.3169,  0.6809, -0.0435,  0.6452]])

# Low Rank Approximation

In [217]:
def low_rank(U, S, Vt, k):
    m, n = U.shape[0], Vt.shape[0]
    C_k = torch.zeros([m,n])
    for i in range(k):
        C_k += S[i] * U[:, [i]] @ Vt[[i], :]
    return C_k

In [218]:
C

tensor([[-0.4823, -1.5105, -0.4407,  3.2276, -0.1590],
        [-0.9366,  0.0962, -2.0062,  0.1766,  1.9826],
        [-1.5003,  0.2550,  0.7925,  0.1977, -1.0079]])

In [221]:
torch.linalg.matrix_rank(C)

tensor(3)

In [219]:
low_rank(U, s, Vt, 1)

tensor([[-0.7215, -1.3562, -0.9432,  3.0135,  0.3831],
        [-0.2156, -0.4053, -0.2819,  0.9007,  0.1145],
        [-0.0115, -0.0216, -0.0150,  0.0480,  0.0061]])

In [220]:
low_rank(U, s, Vt, 2)

tensor([[-0.6895, -1.4535, -0.4345,  3.2084, -0.1817],
        [-0.3251, -0.0719, -2.0243,  0.2332,  2.0493],
        [ 0.0364, -0.1674,  0.7470,  0.3399, -0.8401]])

In [222]:
low_rank(U, s, Vt, 3)

tensor([[-0.4823, -1.5105, -0.4407,  3.2276, -0.1590],
        [-0.9366,  0.0962, -2.0062,  0.1766,  1.9826],
        [-1.5003,  0.2550,  0.7925,  0.1977, -1.0079]])